---
version: '3.4'
services:
  pg:
    image: postgres:11.2
    environment:
      POSTGRES_USER: superuser # not for app purposes!
      POSTGRES_PASSWORD: superuserpwd # not for app purposes!
    volumes:
      - ./docker/tmp/postgres:/var/lib/postgresql/data
      - ./docker/init-user-db.sql:/docker-entrypoint-initdb.d/init-user-db.sql
    ports:
      - 5432:5432 
