// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Election string
	User     string
	Vote     string
}{
	Election: "election",
	User:     "user",
	Vote:     "vote",
}
