// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Alias    string
	Client   string
	Election string
	User     string
	Vote     string
}{
	Alias:    "alias",
	Client:   "client",
	Election: "election",
	User:     "user",
	Vote:     "vote",
}
