CREATE USER rvuser PASSWORD 'rvpass';
CREATE DATABASE rv;
GRANT ALL PRIVILEGES ON DATABASE rv TO rvuser;

CREATE USER testuser PASSWORD 'testpass';
CREATE DATABASE test;
GRANT ALL PRIVILEGES ON DATABASE test TO testuser;
