// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Ballots", testBallots)
	t.Run("Elections", testElections)
}

func TestDelete(t *testing.T) {
	t.Run("Ballots", testBallotsDelete)
	t.Run("Elections", testElectionsDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Ballots", testBallotsQueryDeleteAll)
	t.Run("Elections", testElectionsQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Ballots", testBallotsSliceDeleteAll)
	t.Run("Elections", testElectionsSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Ballots", testBallotsExists)
	t.Run("Elections", testElectionsExists)
}

func TestFind(t *testing.T) {
	t.Run("Ballots", testBallotsFind)
	t.Run("Elections", testElectionsFind)
}

func TestBind(t *testing.T) {
	t.Run("Ballots", testBallotsBind)
	t.Run("Elections", testElectionsBind)
}

func TestOne(t *testing.T) {
	t.Run("Ballots", testBallotsOne)
	t.Run("Elections", testElectionsOne)
}

func TestAll(t *testing.T) {
	t.Run("Ballots", testBallotsAll)
	t.Run("Elections", testElectionsAll)
}

func TestCount(t *testing.T) {
	t.Run("Ballots", testBallotsCount)
	t.Run("Elections", testElectionsCount)
}

func TestHooks(t *testing.T) {
	t.Run("Ballots", testBallotsHooks)
	t.Run("Elections", testElectionsHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Ballots", testBallotsInsert)
	t.Run("Ballots", testBallotsInsertWhitelist)
	t.Run("Elections", testElectionsInsert)
	t.Run("Elections", testElectionsInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("BallotToElectionUsingElection", testBallotToOneElectionUsingElection)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("ElectionToBallots", testElectionToManyBallots)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("BallotToElectionUsingBallots", testBallotToOneSetOpElectionUsingElection)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("ElectionToBallots", testElectionToManyAddOpBallots)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Ballots", testBallotsReload)
	t.Run("Elections", testElectionsReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Ballots", testBallotsReloadAll)
	t.Run("Elections", testElectionsReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Ballots", testBallotsSelect)
	t.Run("Elections", testElectionsSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Ballots", testBallotsUpdate)
	t.Run("Elections", testElectionsUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Ballots", testBallotsSliceUpdateAll)
	t.Run("Elections", testElectionsSliceUpdateAll)
}
